HYDS/HYDS/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^store/',include('store.urls',namespace='store')),
    url(r'^goods/',include('goods.urls',namespace='goods')),
    url(r'^shopcart/',include('shopcart.urls',namespace='shopcart')),
    url(r'^search/',include("haystack.urls")), # 配置检索的路由
    url(r'^orders/',include("orders.urls",namespace='orders')),









    url(r'^',include('users.urls',namespace='users')),


]

HYDS/orders/urls.py
from . import views
from django.conf.urls import url


urlpatterns=[
    url(r'^order_confirm/$',views.order_confirm,name='order_confirm'),
    url(r'^order_done/$',views.order_done,name='order_done'),
    url(r'^order_list/$',views.order_list,name='order_list'),
    url(r'^(?P<o_id>\d+)/del_order/$',views.del_order,name='del_order'),
    url(r'^(?P<o_id>\d+)/order_detail/$',views.order_detail,name='order_detail'),
]

HYDS/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^index/$', views.index,name='index'),
    url(r'^register/$', views.register,name='register'),
    url(r'^logins/$', views.logins,name='logins'),
    url(r'^logouts/$', views.logouts,name='logouts'),
    url(r'^reg_email/$', views.reg_email,name='reg_email'),
    url(r'^get_code/$', views.get_code,name='get_code'),
    url(r'^checkname/$', views.checkname,name='checkname'),
    url(r'^checkemail/$', views.checkemail,name='checkemail'),
    url(r'^userinfo/$', views.userinfo,name='userinfo'),
    url(r'^changeinfo/$', views.changeinfo,name='changeinfo'),
    url(r'^changeavatar/$', views.changeavatar,name='changeavatar'),
    url(r'^changepwd/$', views.changepwd,name='changepwd'),
    #地址
    url(r'^add_addr/$', views.add_addr,name='add_addr'),
    url(r'^addr_update/$', views.addr_update,name='addr_update'),
    url(r'^(?P<addr_id>\d+)/addr_del/$', views.addr_del,name='addr_del'),

    url(r'^.*?$',views.index,name='index'),

]

HYDS/goods/models.py
from django.db import models

from store.models import Store


class GoodsType(models.Model):
    id = models.AutoField(primary_key=True)
    gt_name = models.CharField(max_length=50, verbose_name='商品类型')
    gt_desc = models.CharField(max_length=255, default='这家伙太懒了。。。。', verbose_name='类型描述')

    gt_parent = models.ForeignKey('self', null=True, blank=True)


class Goods(models.Model):
    id = models.AutoField(primary_key=True, verbose_name='商品id')
    name = models.CharField(max_length=50, blank=False, null=False, verbose_name='商品名字')
    price = models.FloatField(verbose_name='商品价格')
    stock = models.IntegerField(verbose_name='商品库存')
    count = models.IntegerField(default=0, verbose_name='商品销量')
    status = models.IntegerField(default=1, verbose_name='商品状态')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='上架时间')
    desc = models.CharField(max_length=255, verbose_name='商品介绍')

    goods_type = models.ForeignKey(GoodsType, on_delete=models.CASCADE)
    goods_store = models.ForeignKey(Store, on_delete=models.CASCADE)


class GoodsImg(models.Model):
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to='static/goods/img/', default='static/goods/img/default.jpg')
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)

HYDS/orders/models.py
from django.db import models
from django.contrib.auth.models import User




class Orders(models.Model):
    id=models.AutoField(primary_key=True,)
    time=models.DateTimeField(auto_now_add=True,)
    total=models.FloatField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    addr=models.CharField(max_length=255,null=False,)
    remark=models.CharField(max_length=255,blank=True)
    status=models.BooleanField(default=True)



class OrdersItem(models.Model):
    id=models.AutoField(primary_key=True)
    goodsimg=models.ImageField(upload_to='static/orders/img')
    goodsname=models.CharField(max_length=50)
    goodsnum=models.IntegerField()
    goodsprice=models.FloatField()
    goodssubtotal=models.FloatField()
    order=models.ForeignKey(Orders,on_delete=models.CASCADE)

HYDS/orders/views.py
from django.shortcuts import render, redirect, HttpResponse
from shopcart.models import ShopCart
from users.models import Address
from . import models
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.views.decorators.http import require_GET, require_POST, require_safe, require_http_methods
from django.db import transaction


# 订单确认
@require_POST
def order_confirm(request):
    total = 0
    # 得到前端勾选的购物车编号
    shopcart_id_list = request.POST.getlist('buy_goods_id')
    # 购物车对象列表
    shopcart_list = ShopCart.objects.filter(pk__in=shopcart_id_list)
    print(shopcart_list, 3333333333)
    for i in shopcart_list:
        # 购物车商品的数量
        print(i.num, 44444444444444)
        # 更新总价
        total += i.subtotal
    addrs = Address.objects.filter(user=request.user)
    # addr=Address.objects.filter(status=True)
    # print(addr,22222222222)
    # 返回到订单确认页面 购物车对象列表，总计，用户所有地址
    return render(request, 'orders/order_confirm.html',
                  {'shopcart_list': shopcart_list, 'total': total, 'addrs': addrs})


# 支付，生成订单

def order_done(request):
    addr = Address.objects.filter(status=True)[0]
    # 地址字符串拼接
    addr = addr.recv + '--' + addr.phone + '--' + addr.province + '--' + addr.city + '--' + addr.qu + '--' + addr.intro
    shopcart_list_id = request.POST.getlist('sc_id')
    total = request.POST.get('total')
    shopcart_list = ShopCart.objects.filter(pk__in=shopcart_list_id)

    # 事务
    o_id = transaction.savepoint()
    try:
        remark = request.POST['remark'].strip()
        if remark != '':
            # 没有留言
            order = models.Orders(addr=addr, remark=remark, user=request.user, total=total)
            order.save()
            for i in shopcart_list:
                goodsname = i.goods.name
                goodsprice = i.goods.price
                goodsnum = i.num
                goodsimg = i.goods.goodsimg_set.all.last().path
                orderitem = models.OrdersItem(goodsimg=goodsimg, goodsname=goodsname, goodsprice=goodsprice,
                                              goodsnum=goodsnum, order=order, goodssubtotal=i.subtotal)
                orderitem.save()
        else:
            order = models.Orders(addr=addr, user=request.user, total=total)
            order.save()
            for i in shopcart_list:
                goodsname = i.goods.name
                goodsprice = i.goods.price
                goodsnum = i.num
                goodsimg = i.goods.goodsimg_set.last().path
                orderitem = models.OrdersItem(goodsimg=goodsimg, goodsname=goodsname, goodsprice=goodsprice,
                                              goodsnum=goodsnum, order=order, goodssubtotal=i.subtotal)
                orderitem.save()
        # 修改商品销量，库存
        for i in shopcart_list:
            if i.goods.stock >= i.num:
                print(i.num, 777777777777777777777777,'购买数量')
                i.goods.stock -= i.num
                i.goods.count += i.num
                i.goods.save()
            else:
                return render(request,'shopcart/shopcart_info.html',{'msg':'库存不足'})

        transaction.savepoint_commit(o_id)
        # return render(request,'orders/order_done.html')
        return redirect('orders:order_list')
    except Exception as e:
        print(e)
        transaction.savepoint_rollback(o_id)


# 订单列表
@login_required
def order_list(request):
    # 筛选 所属用户订单状态为1 的订单
    _order_list = models.Orders.objects.filter(user=request.user, status=True).order_by('-time')
    return render(request, 'orders/order_list.html', {'order_list': _order_list})


# 删除订单
@login_required
def del_order(request, o_id):
    #修改状态为False
    models.Orders.objects.filter(pk=o_id).update(status=False)
    return redirect('orders:order_list')


# 订单详情
@login_required
def order_detail(request, o_id):
    order = models.Orders.objects.filter(pk=o_id)[0]
    orderitems = models.OrdersItem.objects.filter(order=order)
    # orderitems=models.OrdersItem.objects.getlist(order_id=o_id)
    return render(request, 'orders/order_detail.html', {'orderitems': orderitems, 'order': order})

HYDS/orders/templates/orders/order_confirm.html
{% extends 'index.html'%}
{% block title %}确认订单页面{% endblock %}
{% block content %}
<link rel="stylesheet" href="/static/orders/order_confirm.css">
<div id="firmcontent">
    <li class="firm_site">
        <div class="firm_title" style="height: auto">选择收货地址</div>
        <ul>
            <li style="background:url(/static/orders/tubiao_.png) no-repeat;">
                <i class="firm_add"></i>
                <a href="{% url 'users:add_addr' %}">添加新地址</a>
            </li>
            <ul onclick="addr()"><h4>收货地址管理：</h4></ul>
             <h4 >
                    {% for i in addrs %}
                    {% if i.status == 1 %}
                    <p>默认地址：
                        <p> {{i.recv}}  |  {{i.phone}}  |　{{i.province}}　｜　{{i.city}}　｜   {{i.qu}}  |  {{i.intro}}</p>
                    </p>
                    {% endif %}
                    {% empty %}
                    <p>没有地址，快去添加吧！！</p>
                    {% endfor %}
                </h4>
            <hr>
            <br><br>
            <ul id="ad" style="display: none" >
            <form action="/users/addr_update/" method="post">
                {% csrf_token %}
                {% for i in addrs %}
                 {% if i.status == 1 %}
                设为默认：<input type="radio" name='addr_default' value="{{i.id}}" checked><span> {{i.recv}} | {{i.phone}} |　{{i.province}}　｜　{{i.city}}　｜　{{i.intro}} |<a
                    href="{% url 'users:addr_del' i.id %}" onclick="return confirm('确认删除吗？')">删除</a> |
             <input type="submit" value="确定"></span><br><br>
                {% else %}
                设为默认：<input type="radio" name='addr_default' value="{{i.id}}"><span> {{i.recv}} | {{i.phone}} |　{{i.province}}　｜　{{i.city}}　｜　{{i.intro}} |<a
                    href="{% url 'users:addr_del' i.id %}" onclick="return confirm('确认删除吗？')">删除</a> |
             <input type="submit" value="确定"></span><br><br>
                {% endif %}
                {% empty %}
                    <p>没有地址，快去添加吧！！</p>
                {% endfor %}
            </form>
        </ul>

        </ul>
        <div class="site_more">
            <div class="site_moreright">
                <a href="{% url 'users:addr_update' %}">管理收货地址</a>
            </div>
        </div>

    </div>

    <div class="firm_inventory">
        <div class="pay_title">
            商品清单
        </div>
        <div class="firm_table">
            <ul>
                <li class="e_product">商品</li>
                <li class="e_nbsp">商品介绍</li>
                <li class="e_quantity">数量</li>
                <li class="e_price">单价(元)</li>
                <li class="e_subtotle">小计(元)</li>
            </ul>
            <div class="firm_car_product" style="font-size: 16px">
                <div class="firm_1">
                    {% for i in shopcart_list %}
                    <ul>
                        <li class="product1">
                            <img src="/{{i.goods.goodsimg_set.all.last.path}}">
                                <p>{{i.goods.name}}</p>
                        </li>
                        <li class="firm_number" style="margin-top: 30px">
                            <p>{{i.goods.desc}}</p>
                        </li>
                        <li class="firm_number" style="margin-top: 30px">
                            <p>{{i.num}}</p>

                        </li>
                        <li class="firm_price">
                            <p>￥{{i.goods.price}}</p>

                        </li>
                        <li class="firm_price1">
                            <p>￥{{i.subtotal}}</p>

                        </li>

                    </ul>
                    <hr>
                        {% endfor %}
                </div>


            </div>
        </div>
    </div>
    <div class="aggregate">
        <form action="{% url 'orders:order_done' %}" method="post">

            {% csrf_token %}
            <input type="text" name="remark" style="" placeholder="这里留言其他需求">
            <input type="hidden" name="total" value="{{total}}">
            {% for i in shopcart_list %}
            <input type="hidden" value="{{i.id}}" name="sc_id">
            {% endfor %}
        <div class="titel_bottom">
            <input type="submit" class="titel_summent" value="确认订单">
            <div class="titel_aggregate">应付金额<span>￥{{total}}</span></div>
        </div></form>
    </div>

</div>
<script>
    function addr(){
        $('#ad').toggle()
    }
</script>
{% endblock %}

HYDS/orders/templates/orders/order_detail.html
{% extends 'users/userinfo.html' %}

{% block aaa %}
<div class="container">
    <div class="col-md-8 " style="border: solid 1px #888;padding: 30px">
        <h3>订单详情：</h3> <h4><a href="{% url 'orders:del_order' order.id %}">删除订单</a></h4>
        <table class="table table-hover" style="font-size: 16px">
            <tr>
                <td>订单号</td>
                <td>订单地址</td>
                <td>订单总价</td>
                <td>订单时间</td>
                <td>买家留言</td>
            </tr>

            <tr>
            <td> {{order.id}}</td>
            <td> {{order.addr}}</td>
            <td>{{order.total}}</td>
            <td>{{order.time|date:'Y-m-d G:i;s'}}</td>
            <td>{{order.remark}}</td>
            </tr>
            <tr>
                <td>商品图片</td>
                <td>商品名称</td>
                <td>商品数量</td>
                <td>商品价格</td>
                <td>商品小计</td>
            </tr>
            {% for i in orderitems %}
            <tr>
                <td><img src="/{{i.goodsimg}}" height="50px;" width="50px" alt=""></td>
                <td>{{i.goodsname}}</td>
                <td>{{i.goodsnum}}</td>
                <td>{{i.goodsprice}}</td>
                <td>{{i.goodssubtotal}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>


{% endblock %}

HYDS/orders/templates/orders/order_done.html
<h2 style="text-align: center">支付成功,已生成订单,<a href="{% url 'orders:order_detail' order.id %}">查看订单列表</a></h2>

HYDS/orders/templates/orders/order_list.html
{% extends 'users/userinfo.html' %}

{% block aaa %}
<div class="container">
    <div class="col-md-8 " style="border: solid 1px #888;padding: 30px">
        <h4>所有订单：</h4>
        <table class="table table-hover">
            <tr>
                <td>订单号</td>
                <td>订单地址</td>
                <td>订单总价</td>
                <td>订单时间</td>
                <td>订单详情</td>
                <td>订单删除</td>
            </tr>
            <tr>
             {% for i in order_list %}
            <td> {{i.id}}</td>
            <td> {{i.addr|truncatechars:15}}</td>
            <td>{{i.total}}</td>
            <td>{{i.time}}</td>
            <td><a href="{% url 'orders:order_detail' i.id %}">详情</a></td>
            <td><a href="{% url 'orders:del_order' i.id %}">删除</a></td>
            </tr>
            {% empty %}
            <h3>没有订单</h3>
            {% endfor %}
        </table>
    </div>
</div>


{% endblock %}