HYDS/HYDS/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^store/',include('store.urls',namespace='store')),
    url(r'^goods/',include('goods.urls',namespace='goods')),
    url(r'^shopcart/',include('shopcart.urls',namespace='shopcart')),
    url(r'^search/',include("haystack.urls")), # 配置检索的路由
    url(r'^orders/',include("orders.urls",namespace='orders')),









    url(r'^',include('users.urls',namespace='users')),


]

HYDS/orders/urls.py
from . import views
from django.conf.urls import url


urlpatterns=[
    url(r'^order_confirm/$',views.order_confirm,name='order_confirm'),
    url(r'^order_done/$',views.order_done,name='order_done'),
    url(r'^order_list/$',views.order_list,name='order_list'),
    url(r'^(?P<o_id>\d+)/del_order/$',views.del_order,name='del_order'),
    url(r'^(?P<o_id>\d+)/order_detail/$',views.order_detail,name='order_detail'),
]

HYDS/shopcart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^(?P<g_id>\d+)/(?P<num>\d+)/add_shopcart/$',views.add_shopcart,name='add_shopcart'),
    url(r'^(?P<g_id>\d+)/(?P<num>\d+)/shopcart_update/$',views.shopcart_update,name='shopcart_update'),
    url(r'^shopcart_info/$',views.shopcart_info,name='shopcart_info'),
    url(r'^(?P<p_id>\d+)/del_shopcart/$',views.del_shopcart,name='del_shopcart'),
]

HYDS/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^index/$', views.index,name='index'),
    url(r'^register/$', views.register,name='register'),
    url(r'^logins/$', views.logins,name='logins'),
    url(r'^logouts/$', views.logouts,name='logouts'),
    url(r'^reg_email/$', views.reg_email,name='reg_email'),
    url(r'^get_code/$', views.get_code,name='get_code'),
    url(r'^checkname/$', views.checkname,name='checkname'),
    url(r'^checkemail/$', views.checkemail,name='checkemail'),
    url(r'^userinfo/$', views.userinfo,name='userinfo'),
    url(r'^changeinfo/$', views.changeinfo,name='changeinfo'),
    url(r'^changeavatar/$', views.changeavatar,name='changeavatar'),
    url(r'^changepwd/$', views.changepwd,name='changepwd'),
    #地址
    url(r'^add_addr/$', views.add_addr,name='add_addr'),
    url(r'^addr_update/$', views.addr_update,name='addr_update'),
    url(r'^(?P<addr_id>\d+)/addr_del/$', views.addr_del,name='addr_del'),

    url(r'^.*?$',views.index,name='index'),

]

HYDS/goods/models.py
from django.db import models

from store.models import Store


class GoodsType(models.Model):
    id = models.AutoField(primary_key=True)
    gt_name = models.CharField(max_length=50, verbose_name='商品类型')
    gt_desc = models.CharField(max_length=255, default='这家伙太懒了。。。。', verbose_name='类型描述')

    gt_parent = models.ForeignKey('self', null=True, blank=True)


class Goods(models.Model):
    id = models.AutoField(primary_key=True, verbose_name='商品id')
    name = models.CharField(max_length=50, blank=False, null=False, verbose_name='商品名字')
    price = models.FloatField(verbose_name='商品价格')
    stock = models.IntegerField(verbose_name='商品库存')
    count = models.IntegerField(default=0, verbose_name='商品销量')
    status = models.IntegerField(default=1, verbose_name='商品状态')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='上架时间')
    desc = models.CharField(max_length=255, verbose_name='商品介绍')

    goods_type = models.ForeignKey(GoodsType, on_delete=models.CASCADE)
    goods_store = models.ForeignKey(Store, on_delete=models.CASCADE)


class GoodsImg(models.Model):
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to='static/goods/img/', default='static/goods/img/default.jpg')
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)

HYDS/shopcart/models.py
from django.db import models
from goods.models import Goods
from django.contrib.auth.models import User



class ShopCart(models.Model):
    id = models.AutoField(primary_key=True,verbose_name='购物车id')
    num = models.IntegerField(verbose_name='购买数量')
    subtotal = models.FloatField(verbose_name='小计')
    time = models.DateTimeField(auto_now_add=True)
    goods = models.ForeignKey(Goods, verbose_name='购物车商品')
    user = models.ForeignKey(User,on_delete=models.CASCADE)


    def __str__(self):
        return str(self.id)

HYDS/shopcart/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.views.decorators.http import require_GET,require_POST
from goods.models import Goods
from . import models
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required



def add_shopcart(request,g_id,num):
    _goods= Goods.objects.get(pk=g_id)
    #查询购物车是否有商品
    try:
        shopcart=models.ShopCart.objects.get(user=request.user,goods=_goods)
        shopcart.num += int(num)
        subtotal = _goods.price * shopcart.num
        shopcart.subtotal =subtotal
        shopcart.save()
    except:
        subtotal=_goods.price*int(num)
        shopcart=models.ShopCart(user=request.user,goods=_goods,num=num,subtotal=subtotal)
        shopcart.save()
    return HttpResponse('添加成功')


@login_required
def shopcart_info(request):
    shoplist = models.ShopCart.objects.filter(user=request.user).order_by('-time')
    return render(request, 'shopcart/shopcart_info.html', {'shoplist': shoplist})


@login_required
def del_shopcart(requesrt,p_id):
    shopcart=models.ShopCart.objects.get(pk=p_id)
    shopcart.delete()
    return redirect('shopcart:shopcart_info')


@login_required
def shopcart_update(request,g_id,num):
    print(g_id,num)
    #购物车id ，和数量
    shopcart=models.ShopCart.objects.get(pk=g_id)
    print(shopcart.goods.price,2222222222222222222)
    shopcart.num=num
    shopcart.subtotal=int(num)*(shopcart.goods.price)
    shopcart.save()
    return HttpResponse('修改成功')

HYDS/shopcart/templates/shopcart/shopcart_info.html
{% extends 'index.html'%}
{% block title %}购物车页面{% endblock %}
{% block link %}
{% load static %}
<link rel="stylesheet" href="/static/css/style.css">
<link rel="stylesheet" href="/static/css/index.css">
<link rel="stylesheet" href="/static/css/login.css">
<link rel="stylesheet" href="/static/css/product.css">
<link rel="stylesheet" href="/static/css/jqzoom.css">
<link rel="stylesheet" href="/static/css/user.css">
<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="/static/js/index.js"></script>
<script type="text/javascript" src="/static/js/jquery.validate.js"></script>
<script type="text/javascript" src="/static/js/messages_zh.js"></script>
<script type="text/javascript" src="/static/js/jqzoom.pack.1.0.1.js"></script>
<script type="text/javascript" src="/static/js/product.js"></script>
<script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
<link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css">
<script src="/static/shopcart/jquery-1.12.4.min.js"></script>
<script src="/static/js/lib/bootstrap-3.3.7-dist/js/bootstrap.js"></script>


{% endblock %}
{% block s %}{% endblock %}
{% block content %}
<h3 style="color: #b92c28;text-align: center">{{msg}}</h3>
<div class="container">
    <div class="col-md-10 col-md-offset-1">
        <div class="row">
            <form action="{% url 'orders:order_confirm' %}" method="post">
                {% csrf_token %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title"><input type="checkbox" style="width:20px;height: 20px;" name=""
                                                       id="check_all">全选</h2>
                    </div>
                    {% for shop_cart in shoplist %}
                    <div class="panel-body"
                         style="border:solid 1px #ddd;border-left: 1px solid transparent;border-right: 1px solid transparent;">
                        <div class="shop_cart_item ">
                            <div class="col-md-12">

                                <div class="col-md-2 col-md-offset-1">
                                    <input type="checkbox" style="width:20px;height: 20px;" name="buy_goods_id"
                                           value="{{shop_cart.id}}">
                                    <img style="width: 100px;height: 100px;"
                                         src="/{{shop_cart.goods.goodsimg_set.all.last.path}}" alt="">
                                </div>
                                <div class="col-md-8">
                                    <br>
                                    <span class="goods_name size1" style="margin-right: 100px">商品名称：{{shop_cart.goods.name}}</span>
                                    <span class="good_price size1" data-m="{{shop_cart.goods.price}}">
                                        商品价格：{{shop_cart.goods.price}}</span>

                                    <div class="amount_box" style="margin-top: 20px">
                                        <span class="reduce" down_goods_id="{{shop_cart.id}}"
                                              style="cursor: pointer">-</span>
                                        <input style="width: 80px;" type="number" name="count" value="{{shop_cart.num}}"
                                                id = 'sum' class="sum">
                                        <span class="add" up_goods_id="{{shop_cart.id}}"
                                              style="cursor: pointer">+</span>
                                    </div>
                                    <br>
                                    <span class="subtotal size1">小计金额：<span>{{shop_cart.subtotal}}</span></span>
                                </div>
                                <div style="float:right;">
                                    <br><br><br><br>
                                    <a class="del-cart" style="cursor:pointer;" goods_id="{{shop_cart.id}}" href="{% url 'shopcart:del_shopcart' shop_cart.id %}" >删除</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <div class="shop_cart_item">购物车为空,<a style="color:red " href="{% url 'users:index' %}">去购物！</a>
                    </div>
                    {% endfor %}

                </div>
                <button type="submit" class="btn btn-danger">提交订单</button>
            </form>

        </div>
    </div>
</div>


<div class="div_deleted">
    <h1 id="show_del_msg"></h1>
    <ul class='deleted'>

    </ul>
</div>
<div class='h' style='display:none  '>
    <div class="slide">
        <div class="item">
            <a href="goods-1048857.html" title="" target="_blank">
                <img src="http://s.handuyishe.com/images/201608/thumb_img/1471375810213443189.jpg"
                     alt="Soneed韩版2016秋装新款女装低腰毛边磨皮开叉牛仔裤UE6161皛0816"
                     title="Soneed韩版2016秋装新款女装低腰毛边磨皮开叉牛仔裤UE6161皛0816">
            </a>
            <p><a href="goods-1048857.html" title="" target="_blank">Soneed韩版2016秋装新款女装低腰毛边磨皮开叉牛仔裤UE6161皛0816 </a>
            </p>
            <p><span class="price">￥258</span></p>
        </div>
    </div>
</div>
<script src="{% static 'shopcart/js/app/shop_cart_del.js' %}"></script>
<script src="{% static 'shopcart/js/app/shop_cart_info.js' %}"></script>

{% endblock %}