HYDS/HYDS/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^store/',include('store.urls',namespace='store')),
    url(r'^goods/',include('goods.urls',namespace='goods')),
    url(r'^shopcart/',include('shopcart.urls',namespace='shopcart')),
    url(r'^search/',include("haystack.urls")), # 配置检索的路由
    url(r'^orders/',include("orders.urls",namespace='orders')),









    url(r'^',include('users.urls',namespace='users')),


]

HYDS/goods/urls.py
from django.conf.urls import url
from . import views



urlpatterns=[
    url(r'^add_type/$',views.add_type,name='add_type'),
    url(r'^(?P<s_id>\d+)/add_goods/$',views.add_goods,name='add_goods'),
    url(r'^(?P<g_id>\d+)/update_goods/$',views.update_goods,name='update_goods'),
    url(r'^(?P<s_id>\d+)/goods_list/$',views.goods_list,name='goods_list'),
    url(r'^(?P<g_id>\d+)/goods_info/$',views.goods_info,name='goods_info'),

    url(r'^select2/$',views.select2,name='select2'),
    # url(r'^add_goods/$',views.add_goods,name='add_goods'),
    # url(r'^add_goods/$',views.add_goods,name='add_goods'),

]

HYDS/store/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^add/$',views.add,name='add'),
    url(r'^store_list/$',views.store_list,name='store_list'),
    url(r'^(?P<s_id>\d+)/storeinfo/$',views.storeinfo,name='storeinfo'),

    url(r'^(?P<s_id>\d+)/update_store/$',views.update_store,name='update_store'),

]

HYDS/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^index/$', views.index,name='index'),
    url(r'^register/$', views.register,name='register'),
    url(r'^logins/$', views.logins,name='logins'),
    url(r'^logouts/$', views.logouts,name='logouts'),
    url(r'^reg_email/$', views.reg_email,name='reg_email'),
    url(r'^get_code/$', views.get_code,name='get_code'),
    url(r'^checkname/$', views.checkname,name='checkname'),
    url(r'^checkemail/$', views.checkemail,name='checkemail'),
    url(r'^userinfo/$', views.userinfo,name='userinfo'),
    url(r'^changeinfo/$', views.changeinfo,name='changeinfo'),
    url(r'^changeavatar/$', views.changeavatar,name='changeavatar'),
    url(r'^changepwd/$', views.changepwd,name='changepwd'),
    #地址
    url(r'^add_addr/$', views.add_addr,name='add_addr'),
    url(r'^addr_update/$', views.addr_update,name='addr_update'),
    url(r'^(?P<addr_id>\d+)/addr_del/$', views.addr_del,name='addr_del'),

    url(r'^.*?$',views.index,name='index'),

]

HYDS/store/models.py
from django.db import models
from django.contrib.auth.models import User


class Store(models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50,verbose_name='店铺名字')
    cover=models.ImageField(upload_to='static/store/cover/',default='static/store/cover/default.jpg',verbose_name='店铺图片')
    intro=models.CharField(max_length=255,default='这家伙很懒，什么都没写',verbose_name='店铺介绍')
    opentime=models.DateTimeField(auto_now_add=True,verbose_name='开店时间')
    status=models.IntegerField(default=1,verbose_name='店铺状态',null=False)

    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='店铺主人')

HYDS/store/views.py
from django.shortcuts import render,redirect,reverse
from . import models
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required



#开店
@login_required
def add(request):
    if request.method=='GET':
        return render(request,'store/add.html',)
    elif request.method=='POST':
        name=request.POST['name'].strip()

        if name=='':
            return render(request,'store/add.html',{'msg':'店铺名字为空'})

        try:
            intro = request.POST['intro'].strip()
            cover = request.FILES['cover']
            store=models.Store(name=name,intro=intro,cover=cover,user=request.user)
            store.save()
            return redirect('store:store_list')
        except Exception as e :
            print(e)
            store = models.Store(name=name, user=request.user)
            store.save()
            return redirect('store:store_list')

#店铺列表
@login_required
def store_list(request):
    store_lists=models.Store.objects.filter(user=request.user)
    return render(request,'store/store_list.html',{'lists':store_lists})


#店铺详情
@login_required
def storeinfo(request,s_id):
    store=models.Store.objects.get(pk=s_id)

    return render(request,'store/storeinfo.html',{'store':store})


#店铺修改
@login_required
def update_store(request,s_id):

    store=models.Store.objects.get(pk=s_id)
    if request.method=='GET':
        return render(request,'store/update_store.html',{'store':store})
    elif request.method=='POST':
        name=request.POST['name'].strip()
        intro=request.POST['intro'].strip()
        status = request.POST['status'].strip()

        if name=='':
            return render(request,'store/update_store.html',{'msg':'店铺名字为空'})
        if intro =='':
            return render(request,'store/update_store.html',{'msg':'店铺介绍为空'})
        store.name = name
        store.intro = intro
        store.status = status
        try:
            cover = request.FILES['cover']
            store.cover=cover
        except Exception as e :
            print(e,'没有上传头像')
            pass
        store.save()
        return redirect(reverse('store:storeinfo',kwargs={'s_id':s_id}))

HYDS/store/templates/store/add.html
{% extends 'users/userinfo.html' %}

{% block aaa %}
<div class="container-fluid">
                <div class="row">
                    <div class="col-md-7 col-md-offset-2">
                       <form action="{% url 'store:add' %}" name="formMobile" id="formMobile" style="display:block" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<ul class="">
							<li>
								<div class="register-list-name">店铺名字：</div>
								<input id='name' type="text" value="" class="" name="name" />
							</li>
							<li style="margin-top: 20px">
								<div class="register-list-name">店铺介绍：</div>
								<textarea name="intro" cols="30" rows="10"></textarea>
							</li>
							<li style="margin-left: 120px">
								<div class="register-list-con register_tipsBox1">
                                    <input type="file"value="" name="cover">
								</div>
							</li>
							<li>
								<input type="submit" id="btn" value="开店" class="register-list-agree" id='register_submit'/>
							</li>
						</ul>
					</form>
                    </div>

                </div>
            </div>
{% endblock %}

HYDS/store/templates/store/store_list.html
{% extends 'users/userinfo.html' %}

{% block aaa %}
<div class="container-fluid">
  <div class="row">
      <div class="col-md-12 col-md-offset-0">
          <table class="table table-bordered table-hover table-striped" >
              <tr>
                  <td>店铺封面</td>
                  <td>店铺标识</td>
                  <td>店铺名字</td>
                  <td>店铺介绍</td>
                  <td>店铺状态</td>

                  <td>店铺详情</td>
              </tr>
              {% for i in lists %}
            <tr>
                <td ><img src="/{{i.cover}}" alt="" class="img-circle" width="100px" height="100px"></td>
                <td style="line-height: 100px;">{{i.id}}</td>
                <td style="line-height: 100px;">{{i.name}}</td>
                <td style="line-height: 100px;">{{i.intro}}</td>
                {% if i.status == 1 %}
                <td style="line-height: 100px;">---营业中---</td>
                {% elif i.status == 0 %}
                <td style="line-height: 100px;">---歇业了---</td>
                {% elif i.status == 2 %}
                <td style="line-height: 100px;">---店铺关闭---</td>
                {% endif %}

                <td ><a href="{% url 'store:storeinfo' i.id %}"><button type="button"  style="height: 35px;margin-top: 35px;background:#c80a28;width: 90px;" >店铺详情</button></a></td>
            </tr>
              {% empty%}
              <tr>
                <td>没有店铺 <a href="{% url 'store:add' %}">快去开店吧</a> </td>
            </tr>
              {% endfor %}

          </table>

      </div>
  </div>
</div>

{% endblock%}

HYDS/store/templates/store/storeinfo.html
{% extends 'index.html' %}
{% block title%}用户信息{% endblock %}
{% block s%}
<div class="search">
			<form action="" method="">
				<input class="txt" type="text">
				<input class="search-btn"  type="button" value="搜索">
			</form>
		</div>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css">
<script src="/static/js/lib/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<div class="user_main">
    <div class="user_wrap">
        <h1 class="crumbs" style="font-weight:100">
            您当前的位置:<a href="" target="_blank">韩都衣舍</a> &gt; <a href="" target="_blank">我的韩都</a>
        </h1>
        <div class="user_left">
            <a href="" class="home">
                <span>我的韩都</span>
            </a>
            <div class="nav">
                <dl class="menu">
                    <dt>个人信息<span class="arrow"></span></dt>
                    <dd>
                        <ul>
                            <li><a href="{% url 'users:userinfo' %}">个人信息</a></li>
                            <li><a href="{% url 'users:changeinfo' %}">修改信息</a></li>
                            <li><a href="">地址管理</a></li>
                        </ul>
                    </dd>
                </dl>
                <dl class="menu">
                    <dt>交易管理<span class="arrow"></span></dt>
                    <dd>
                        <ul>
                            <li><a href="" target="_blank">我的购物车</a></li>
                            <li><a href="">我的订单</a></li>
                            <li class="last"><a href="user.php?act=collection_list">我的收藏</a></li>
                        </ul>
                    </dd>
                </dl>
                <dl class="menu">
                    <dt>店铺管理<span class="arrow"></span></dt>
                    <dd>
                        <ul>
                            <li><a href="{% url 'store:add' %}">我要开店</a></li>
                            <li><a href="">上传商品</a></li>
                            <li><a href="{% url 'goods:add_type' %}">添加商品类型</a></li>
                            <li><a href="{% url 'store:store_list' %}" target="_blank">我的所有店铺</a></li>

                            <li class="last"><a href="">在线客服</a></li>
                        </ul>
                    </dd>
                </dl>
                <dl class="menu">
                    <dt>账户管理<span class="arrow"></span></dt>
                    <dd>
                        <ul>
                            <li><a href="">我的特权</a></li>
                            <li><a href="">我的积分</a></li>
                            <li><a href="">我的优惠券</a></li>
                            <li><a href="">我的包邮卡</a></li>
                            <li><a href="">SVIP激活</a></li>
                            <li><a href="">护理液兑换码</a></li>
                        </ul>
                    </dd>
                </dl>

            </div>
        </div>

        <div class="user_right">
            <h5 style="text-align: center ; color: red ;">{{msg}}</h5>
            {% block aaa %}
            <div class="container-fluid">
                <div class="row">

                    <div class="col-md-7 col-md-offset-2">
                        <ul class="list-group" style="text-align:center">
                            <li class="list-group-item">
                                <img src="/{{store.cover}}" alt="用户头像" class="img-circle avatar"
                                     width="200px" height="200px" style="margin: auto">
                            </li>
                            <li class="list-group-item " style="">
                                店铺标识：{{store.id}}
                            </li>
                            <li class="list-group-item" style=" ">
                                店铺名称：{{store.name}}
                            </li>
                            <li class="list-group-item" style=" ">
                                店铺介绍：{{store.intro}}
                            </li>
                            <li class="list-group-item" style=" ">
                                开店时间：{{store.opentime}}
                            </li>
                            <li class="list-group-item" style=" ">
                                店铺状态：
                                 {% if store.status == 1 %}
                                <td style="line-height: 100px;">---营业中---</td>
                                {% elif store.status == 0 %}
                                <td style="line-height: 100px;">---歇业了---</td>
                                {% elif store.status == 2 %}
                                <td style="line-height: 100px;">---店铺关闭---</td>
                                {% endif %}

                            </li>
                            <li class="list-group-item" >
                                <a href="{% url 'goods:add_goods' store.id %}"><input type="button" style="margin-left: -20px" class="register-list-agree" value="添加商品"></a>
                            </li>
                            <li class="list-group-item" >
                                <a href="{% url 'store:update_store' store.id %}"><input type="button" style="margin-left: -20px" class="register-list-agree" value="修改店铺"></a>
                            </li>
                            <li class="list-group-item" >
                                <a href="{% url 'goods:goods_list' store.id %}"><input type="button" style="margin-left: -20px" class="register-list-agree" value="商品列表"></a>
                            </li>
                        </ul>
                    </div>

                </div>
            </div>
            {% endblock %}
        </div>

    </div>
</div>
<script type="text/javascript">
    $(function () {

        $(".menu dt").each(function () {
            $(this).click(function () {
                if ($(this).next().is(":hidden")) {
                    $(this).removeClass("hid");
                    $(this).next().show();
                } else {
                    $(this).addClass("hid");
                    $(this).next().hide();

                }
            });
        });

    });
</script>
{% endblock %}

HYDS/store/templates/store/update_store.html
{% extends 'users/userinfo.html' %}

{% block aaa %}
<div class="container-fluid">
                <div class="row">
                    <div class="col-md-7 col-md-offset-2">
                       <form action="{% url 'store:update_store' store.id %}" name="formMobile" id="formMobile" style="display:block" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<ul class="">
							<li>
								<div class="register-list-name">店铺名字：</div>
								<input id='name' type="text" value="{{store.name}}" class="" name="name" />
							</li>
							<li style="margin-top: 20px">
								<div class="register-list-name">店铺介绍：</div>
								<textarea name="intro">{{store.intro}}</textarea>
							</li>
							<li style="margin-top: 20px">
								<div class="register-list-name">店铺状态：</div>
                                {% if store.status == 1 %}
                                <input type="radio" name="status" value="1" checked>营业
                                <input type="radio" name="status" value="0">歇业
                                <input type="radio" name="status" value="2">闭店
                                 {% elif store.status == 0 %}
                                <input type="radio" name="status" value="1" >营业
                                <input type="radio" name="status" value="0" checked>歇业
                                <input type="radio" name="status" value="2">闭店
                                 {% elif store.status == 2 %}
                                <input type="radio" name="status" value="1" >营业
                                <input type="radio" name="status" value="0">歇业
                                <input type="radio" name="status" value="2" checked>闭店
                                {% endif%}
							</li>
                            <li style="margin-left: 120px">
                                <img src="/{{store.cover}}" alt="" style="width: 200px;height: 200px;">
								<div class="register-list-con register_tipsBox1">
                                    <input type="file" name="cover" >
								</div>
							</li>
							<li>
								<input type="submit" id="btn" value="修改店铺" class="register-list-agree" onclick="return confirm('确认修改吗？')" id='register_submit'/>
							</li>
						</ul>
					</form>
                    </div>

                </div>
            </div>

{% endblock%}