HYDS/HYDS/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^store/',include('store.urls',namespace='store')),
    url(r'^goods/',include('goods.urls',namespace='goods')),
    url(r'^shopcart/',include('shopcart.urls',namespace='shopcart')),
    url(r'^search/',include("haystack.urls")), # 配置检索的路由
    url(r'^orders/',include("orders.urls",namespace='orders')),









    url(r'^',include('users.urls',namespace='users')),


]

HYDS/goods/urls.py
from django.conf.urls import url
from . import views



urlpatterns=[
    url(r'^add_type/$',views.add_type,name='add_type'),
    url(r'^(?P<s_id>\d+)/add_goods/$',views.add_goods,name='add_goods'),
    url(r'^(?P<g_id>\d+)/update_goods/$',views.update_goods,name='update_goods'),
    url(r'^(?P<s_id>\d+)/goods_list/$',views.goods_list,name='goods_list'),
    url(r'^(?P<g_id>\d+)/goods_info/$',views.goods_info,name='goods_info'),

    url(r'^select2/$',views.select2,name='select2'),
    # url(r'^add_goods/$',views.add_goods,name='add_goods'),
    # url(r'^add_goods/$',views.add_goods,name='add_goods'),

]

HYDS/orders/urls.py
from . import views
from django.conf.urls import url


urlpatterns=[
    url(r'^order_confirm/$',views.order_confirm,name='order_confirm'),
    url(r'^order_done/$',views.order_done,name='order_done'),
    url(r'^order_list/$',views.order_list,name='order_list'),
    url(r'^(?P<o_id>\d+)/del_order/$',views.del_order,name='del_order'),
    url(r'^(?P<o_id>\d+)/order_detail/$',views.order_detail,name='order_detail'),
]

HYDS/shopcart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^(?P<g_id>\d+)/(?P<num>\d+)/add_shopcart/$',views.add_shopcart,name='add_shopcart'),
    url(r'^(?P<g_id>\d+)/(?P<num>\d+)/shopcart_update/$',views.shopcart_update,name='shopcart_update'),
    url(r'^shopcart_info/$',views.shopcart_info,name='shopcart_info'),
    url(r'^(?P<p_id>\d+)/del_shopcart/$',views.del_shopcart,name='del_shopcart'),
]

HYDS/store/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^add/$',views.add,name='add'),
    url(r'^store_list/$',views.store_list,name='store_list'),
    url(r'^(?P<s_id>\d+)/storeinfo/$',views.storeinfo,name='storeinfo'),

    url(r'^(?P<s_id>\d+)/update_store/$',views.update_store,name='update_store'),

]

HYDS/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^index/$', views.index,name='index'),
    url(r'^register/$', views.register,name='register'),
    url(r'^logins/$', views.logins,name='logins'),
    url(r'^logouts/$', views.logouts,name='logouts'),
    url(r'^reg_email/$', views.reg_email,name='reg_email'),
    url(r'^get_code/$', views.get_code,name='get_code'),
    url(r'^checkname/$', views.checkname,name='checkname'),
    url(r'^checkemail/$', views.checkemail,name='checkemail'),
    url(r'^userinfo/$', views.userinfo,name='userinfo'),
    url(r'^changeinfo/$', views.changeinfo,name='changeinfo'),
    url(r'^changeavatar/$', views.changeavatar,name='changeavatar'),
    url(r'^changepwd/$', views.changepwd,name='changepwd'),
    #地址
    url(r'^add_addr/$', views.add_addr,name='add_addr'),
    url(r'^addr_update/$', views.addr_update,name='addr_update'),
    url(r'^(?P<addr_id>\d+)/addr_del/$', views.addr_del,name='addr_del'),

    url(r'^.*?$',views.index,name='index'),

]

HYDS/users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserInfo(models.Model):
    id=models.AutoField(primary_key=True,verbose_name='用户标识')
    # username=models.CharField(max_length=100,null=False,unique=True,verbose_name='用户名')
    nickname=models.CharField(max_length=100,null=False,default='匿名用户',verbose_name='用户昵称')
    age=models.IntegerField(default=18,verbose_name='年龄')
    # email=models.CharField(max_length=100,default='110@qq.com',verbose_name='邮箱')
    sex=models.CharField(max_length=10,default='男',verbose_name='性别')
    phone=models.CharField(max_length=50,default=123456,verbose_name='联系方式')
    # createtime=models.DateTimeField(auto_now_add=True,verbose_name='注册时间')
    avatar=models.ImageField(upload_to='static/users/avatar/',default='static/users/avatar/default.jpg')
   #一对一外键
    user=models.OneToOneField(User,on_delete=models.CASCADE)


class Address(models.Model):
    id=models.AutoField(primary_key=True,verbose_name='dizhi_id')
    recv=models.CharField(max_length=50)
    phone=models.CharField(max_length=50,verbose_name='手机号')
    diqu=models.CharField(max_length=50,verbose_name='diqu')
    province=models.CharField(max_length=50,verbose_name='')
    city=models.CharField(max_length=50,verbose_name='')
    qu=models.CharField(max_length=50,verbose_name='')
    intro=models.CharField(max_length=255,verbose_name='')
    status=models.BooleanField(default=False,verbose_name='')

    user = models.ForeignKey(User,on_delete=models.CASCADE)

HYDS/users/views.py
from django.shortcuts import render,redirect,reverse,HttpResponse
from . import models
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
#检查用户
from django.contrib.auth import authenticate,login,logout
from django.db import transaction

from . utils import create_code
from io import BytesIO
from django.conf import settings
from django.core.mail import send_mail
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from django.http import JsonResponse
from goods.models import Goods
from store.models import Store
from utils import utils
from django.core.paginator import Paginator
from goods.models import GoodsType


#主页
def index(request):
    # 当前页
    pageNow = int(request.GET.get('pageNow', 1))
    # 展示所有商品
    goods = utils.cache_allgoods()
    pagesize = settings.PAGESIZE
    paginator = Paginator(goods, pagesize)
    page = paginator.page(pageNow)
    #查找一级类型
    goodstype1=GoodsType.objects.filter(gt_parent__isnull=True)
    #查找二 级类型
    goodstype2=GoodsType.objects.filter(gt_parent__isnull=False)

    #找到店铺状态为营业的店列表
    stores=Store.objects.filter(status=1)
    #找到营业的店的商品
    goods=Goods.objects.filter(goods_store_id__in=stores)
    return render(request,'index.html',{'goods':goods,'page':page})


# 注册函数
def register(request):
    if request.method == 'GET':
        return render(request, 'users/register.html', {'msg': '请输入信息'})
    else:
        username = request.POST['name'].strip()
        password = request.POST['pwd'].strip()
        confirm = request.POST['confirm'].strip()
        code = request.POST['code'].strip()
        if username == '':
            return render(request, 'users/register.html', {'msg': '用户名不能为空！'})
        if len(password) < 6:
            return render(request, 'users/register.html', {'msg': '密码小于6位'})
        if password != confirm:
            return render(request, 'users/register.html', {'msg': '两次密码不一致！'})

        if request.session['code'].upper() != code.upper():
            return render(request, 'users/register.html', {'msg': '验证码错误'})
        try:
            # 判断用户名是否已注册 get 查找到0或多条都会报错
            User.objects.get(username=username)
            return render(request, 'users/register.html', {'msg': '用户名已存在'})
        except:
            try:
                user = User.objects.create_user(username=username, password=password)
                userinfo=models.UserInfo(user=user)
                user.save()
                userinfo.save()
            # 跳转到登录页面
                return redirect('users:logins')
                # return render(request, "users/login.html", {"msg": "注册成功,请登录!"})
            except Exception as e:
                print(e,2222222222222222222222)
                return render(request, "users/register.html", {"msg": "注册失败!"})


# 登录
def logins(request):
    if request.method == 'GET':
        request.session['num'] = 0
        try:
            next_url = request.GET['next']
        except:
            next_url = '/users/index/'
        print(next_url)
        request.session['next'] = next_url
        return render(request, 'users/login.html', {'msg': '请填写登录信息！'})
    elif request.method == 'POST':
        request.session['num'] += 1
        username = request.POST['name'].strip()
        password = request.POST['pwd'].strip()
        # next_url = request.POST.get('next', '/users/index/')
        next_url=request.session['next']
        print(next_url,'要跳转的页面链接')
        # 判断验证码
        if request.session['num'] > 2:
            print(request.session['num'], '登录错误次数')
            try:
                code = request.POST['code'].strip()
                if request.session['code'].upper() != code.upper():
                    return render(request, 'users/login.html', {'msg': '验证码错误'})
                else:
                    pass
            except:
                return render(request, 'users/login.html', {'msg': '填写验证码'})

        # 判断用户
        user= authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                del request.session['next']
                return redirect(next_url)
                # return redirect('/users/index/')
            else:
                return render(request, 'users/login.html', {'error_code': 2, 'msg': '账号被锁定'})
        else:
            return render(request, 'users/login.html', {'msg': '用户名或密码错误'})

#退出
@login_required
def logouts(request):
    logout(request)
    return redirect('users:index')

# 获取验证码
def get_code(request):
    img, code = create_code()
    f = BytesIO()
    request.session['code'] = code
    img.save(f, 'PNG')
    return HttpResponse(f.getvalue())


# 邮箱注册
def reg_email(request):
    if request.method == "GET":
        return render(request, "users/register.html", {})
    else:
        email = request.POST["email"].strip()
        password = request.POST.get("pwd").strip()
        confirmpwd = request.POST.get("confirm").strip()
        code = request.POST['code'].strip()
    # 数据校验
    if request.session['code'] !=code:
        return render(request, "users/register.html", {"msg": "验证码错误！！"})
    if len(email) < 1:
        return render(request, "users/register.html", {"msg": "用户邮箱为空！！"})
    if len(password) < 4:
        return render(request, "users/register.html", {"msg": "长度小于 4 位！！"})
    if password != confirmpwd:
        return render(request, "users/register.html", {"msg": "两次密码不一致！！"})
    try:
        user =User.objects.get(username=email)
        return render(request, "users/register.html", {"msg": "名称已经存在"})
    except:

        user = User.objects.create_user(username=email, password=password,email=email)
        userinfo = models.UserInfo(user=user)
    try:
        user.save()
        userinfo.save()
        try:
            # 保存成功，发送邮件
            m_title = "wqx测试电商账号激活邮件"
            m_msg = "点击激活您的账号"
            # 调用 JWT 来加密和解密需要的数据
            serializer = Serializer(settings.SECRET_KEY, expires_in=3600)
            code = serializer.dumps({"confirm": user.id}).decode("utf-8")
            href = "http://ww.ljh.com/blog/active/" + code + "/"
            m_html = '<a href="' + href + '" target="_blank">马上点击激活，一个小时内有效</a>'
            send_mail(m_title, m_msg, settings.EMAIL_FROM, [email], html_message=m_html)
            return render(request, "users/login.html", {"msg": "恭喜您，注册成功，请登录邮箱激活账号！！"})
        except Exception as e:
            print(e,111111111111111)
            return render(request, "users/login.html", {"msg": "恭喜您，注册成功，邮箱发送失败，请点击重新发送"})
    except Exception as e:
        return render(request, "users/register.html", {"msg": "注册失败，请重新注册，或者联系管理员"})


def active(request, token):
    serializer = Serializer(settings.SECRET_KEY, 3600)
    try:
        info = serializer.loads(token)
        active_id = info["confirm"]
        user = models.User.objects.get(pk=active_id)
        user.is_active = True
        user.save()
        return render(request, "users/login.html", {"msg": "恭喜您，激活账号成功，请登录！！"})
    except Exception as e:
        return HttpResponse("激活失败")


#ajax 检查名字
def checkname(request):
    name=request.GET['name'].strip()
    try:
        user=User.objects.get(username=name)
        return JsonResponse({'msg':'该账号已存在,请更换 ','success':False})
    except:
        return JsonResponse( {'msg': '该账号可用','success':True})


#ajax 检查名字
def checkemail(request):
    email=request.GET['email'].strip()
    try:
        user=User.objects.get(username=email)
        return JsonResponse({'msg':'该账号已存在,请更换 ','success':False})
    except:
        return JsonResponse( {'msg': '该账号可用','success':True})



# 展示个人信息
@login_required
def userinfo(request):
    user = request.user
    return render(request, 'users/userinfo.html', {'user': user})


# 修改资料
@login_required
def changeinfo(request):
    user = request.user
    if request.method == 'GET':
        return render(request, 'users/changeinfo.html', {'user': user})

    else:
        nickname = request.POST['nickname'].strip()
        age = request.POST['age'].strip()
        email = request.POST['email'].strip()
        phone = request.POST['phone'].strip()
        sex = request.POST['sex'].strip()

        if nickname == '':
            return render(request, 'users/changeinfo.html', {'msg': '昵称不能为空'})
        # 年龄要判断
        if age == '' or int(age) < 0 or int(age) > 120:
            return render(request, 'users/changeinfo.html', {'msg': '年龄输入有误'})
        if email == '':
            return render(request, 'users/changeinfo.html', {'msg': '邮箱不能为空'})
        if phone == '':
            return render(request, 'users/changeinfo.html', {'msg': '手机号不能为空'})

        try:
            user.userinfo.nickname = nickname
            user.userinfo.age = age
            user.email = email
            user.userinfo.phone = phone
            user.userinfo.sex = sex
            user.save()
            user.userinfo.save()

            # 重定向到个人信息页面
            return redirect('/users/userinfo/')
        except Exception as e:
            print(e)
            return render(request, 'users/changeinfo.html', {'msg': '信息修改失败！！！'})


# 修改头像
@login_required
def changeavatar(request):
    user = request.user
    if request.method == 'GET':
        return render(request, 'users/changeinfo.html', {'user': user})
    else:
        avatar = request.FILES['avatar']
        try:
            user.userinfo.avatar = avatar
            user.userinfo.save()
            return redirect('/users/userinfo/')
        except:
            return render(request, 'users/changeinfo.html', {"msg": '头像修改失败！！'})


# 修改密码
@login_required
def changepwd(request):
    user = request.user
    if request.method == 'GET':
        return render(request, 'users/changeinfo.html', {'user': user})

    else:
        oldpwd = request.POST['oldpwd'].strip()
        newpwd = request.POST['newpwd'].strip()
        confirm = request.POST['confirm'].strip()
        if len(newpwd) < 6:

HYDS/users/templates/users/changeinfo.html
{% extends 'users/userinfo.html' %}

{% block aaa %}

<div class="container-fluid">
    <div class="row">
            <div class="col-md-7 col-md-offset-2">
                <div>
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#info" aria-controls="home"
                                                                  role="tab"
                                                                  data-toggle="tab">修改基本资料</a></li>
                        <li role="presentation"><a href="#avatar" aria-controls="profile" role="tab"
                                                   data-toggle="tab">修改头像</a></li>
                        <li role="presentation"><a href="#mima" aria-controls="messages" role="tab"
                                                   data-toggle="tab">修改密码</a></li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="info">
                            <div class="panel panel-default zhuce1">
                                <div class="panel-body">
                                    <form class="form-horizontal" action="{% url 'users:changeinfo' %}"
                                          method="post">
                                        {% csrf_token %}
                                        <div class="form-group">

                                            <div class="col-md-10">
                                                <label for="inputusername1">用户名称</label>
                                                <input type="text" class="form-control"
                                                       name="name" id="inputusername1"
                                                       value="{{user.username}}" disabled>
                                            </div>
                                        </div>
                                        <div class="form-group">

                                            <div class="col-md-10">
                                                <label for="inputusername2">用户昵称</label>
                                                <input type="text" class="form-control"
                                                       name="nickname" id="inputusername2"
                                                       value="{{user.userinfo.nickname}}">
                                            </div>
                                        </div>

                                        <div class="form-group">

                                            <div class="col-md-10">
                                                <label for="inputusername3">用户年龄</label>
                                                <input type="text" class="form-control"
                                                       name="age" id="inputusername3"
                                                       value="{{user.userinfo.age}}">
                                            </div>
                                        </div>

                                        <div class="form-group">

                                            <div class="col-md-10">
                                                <label for="inputusername5">用户邮箱</label>
                                                <input type="text" class="form-control"
                                                       name="email" id="inputusername5"
                                                       value="{{user.email}}">
                                            </div>
                                        </div>
                                        <div class="form-group">

                                            <div class="col-md-10">
                                                <label for="inputusername6">用户电话</label>
                                                <input type="text" class="form-control"
                                                       name="phone" id="inputusername6"
                                                       value="{{user.userinfo.phone}}">
                                            </div>
                                        </div>
                                        <div class="form-group">

                                            <div class="col-md-12">
                                                <label for="inputusername4">用户性别</label>
                                                {% if user.sex == '男'%}
                                                <input type="radio" class=""
                                                       name="sex" id="inputusername4" value="男" checked>男
                                                <input type="radio" class=""
                                                       name="sex" id="inputusername4" value="女">女
                                                {% else %}
                                                <input type="radio" class=""
                                                       name="sex" id="inputusername4" value="男">男
                                                <input type="radio" class=""
                                                       name="sex" id="inputusername4" value="女" checked>女
                                                {% endif %}
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-sm-12">
                                                <button type="submit" class="btn btn-primary  zhucebtn2">提交
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane " id="avatar">
                            <div class="panel panel-default zhuce1">

                                <div class="panel-body">
                                    <form class="form-horizontal" action="{% url 'users:changeavatar' %}"
                                          method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="form-group">

                                            <div class="col-md-10">
                                                <img src="/{{user.userinfo.avatar}}" alt=""
                                                     style="width: 300px;height: 300px" id="img">
                                            </div>
                                        </div>
                                        <div class="form-group ">
                                            <div class="col-sm-10">
                                                <input type="file" class="btn btn-primary " name="avatar">

                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-sm-10">
                                                <button type="submit" class="btn btn-primary  zhucebtn2">提交
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                        <div role="tabpanel" class="tab-pane " id="mima">
                            <div class="panel panel-default zhuce1">
                                <div class="panel-body">
                                    <form class="form-horizontal" action="{% url 'users:changepwd' %}"
                                          method="post">
                                        {% csrf_token %}
                                        <div class="form-group">

                                            <div class="col-md-10">
                                                <label for="pwd1">旧密码</label>
                                                <input type="password" class="form-control"
                                                       name="oldpwd" id="pwd1" value="">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <label for="pwd2">新密码</label>
                                                <input type="password" class="form-control"
                                                       name="newpwd" id="pwd2">
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <label for="pwd3">确认密码</label>
                                                <input type="password" class="form-control"
                                                       name="confirm" id="pwd3">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-12">
                                                <button type="submit" class="btn btn-primary  zhucebtn2">提交
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</div>


{% endblock %}

HYDS/users/templates/users/userinfo.html
{% extends 'index.html' %}
{% block title%}用户信息{% endblock %}
{% block s%}
<div class="search">
			<form action="" method="">
				<input class="txt" type="text">
				<input class="search-btn"  type="button" value="搜索">
			</form>
		</div>
{% endblock %}

{% block content %}

<link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css">
<script src="/static/js/lib/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<div class="user_main">
    <div class="user_wrap">
        <h1 class="crumbs" style="font-weight:100">
            您当前的位置:<a href="" target="_blank">韩都衣舍</a> &gt; <a href="" target="_blank">我的韩都</a>
        </h1>
        <div class="user_left">
            <a href="" class="home">
                <span>我的韩都</span>
            </a>
            <div class="nav">
                <dl class="menu">
                    <dt>个人信息<span class="arrow"></span></dt>
                    <dd>
                        <ul>
                            <li><a href="{% url 'users:userinfo' %}">个人信息</a></li>
                            <li><a href="{% url 'users:changeinfo' %}">修改信息</a></li>
                            <li><a href="{% url 'users:add_addr' %}">添加地址</a></li>
                            <li><a href="{% url 'users:addr_update' %}">地址管理</a></li>
                            <li><a href="/admin/">后台管理</a></li>
                        </ul>
                    </dd>
                </dl>
                <dl class="menu">
                    <dt>交易管理<span class="arrow"></span></dt>
                    <dd style="width: 150px">
                        <ul>
                            <li><a href="{% url 'shopcart:shopcart_info'%}" target="_blank">我的购物车</a></li>
                            <li><a href="{% url 'orders:order_list' %}">我的订单</a></li>
                            <li class="last"><a href="user.php?act=collection_list">我的收藏</a></li>
                        </ul>
                    </dd>
                </dl>
                <dl class="menu">
                    <dt>店铺管理<span class="arrow"></span></dt>
                    <dd style="width: 150px">
                        <ul>
                            <li><a href="{% url 'store:add' %}">我要开店</a></li>
                            <li><a href="{% url 'goods:add_type' %}">添加商品类型</a></li>
                            <li><a href="{% url 'store:store_list' %}" target="_blank">我的所有店铺</a></li>

                        </ul>
                    </dd>
                </dl>
                <dl class="menu" >
                    <dt>账户管理<span class="arrow"></span></dt>
                    <dd style="width: 150px">
                        <ul>
                            <li><a href="">我的特权</a></li>
                            <li><a href="">我的积分</a></li>
                            <li><a href="">我的优惠券</a></li>
                            <li><a href="">我的包邮卡</a></li>
                            <li><a href="">SVIP激活</a></li>
                        </ul>
                    </dd>
                </dl>

            </div>
        </div>

        <div class="user_right">
            <h5 style="text-align: center ; color: red ;">{{msg}}</h5>
            {% block aaa %}
            <div class="container-fluid">
                <div class="row">

                    <div class="col-md-9 col-md-offset-2">
                        <ul class="list-group" style="text-align:center;font-size: 17px">
                            <li class="list-group-item">
                                <img src="/{{user.userinfo.avatar}}" alt="用户头像" class="img-circle avatar"
                                     width="200px" height="200px" style="margin: auto">
                            </li>
                            <li class="list-group-item " style="">
                                用户标识：{{user.id}}
                            </li>
                            <li class="list-group-item" style=" ">
                                用户名称：{{user.username}}
                            </li>
                            <li class="list-group-item" style=" ">
                                用户昵称：{{user.userinfo.nickname}}
                            </li>
                            <li class="list-group-item" style=" ">
                                用户性别：{{user.userinfo.sex}}
                            </li>
                            <li class="list-group-item" style=" ">
                                用户年龄：{{user.userinfo.age}}
                            <li class="list-group-item" style=" ">
                                用户邮箱：{{user.email}}
                            </li>
                            <li class="list-group-item" style=" ">
                                用户电话：{{user.userinfo.phone}}
                            </li>
                            <li class="list-group-item" style=" ">
                                注册时间：{{user.date_joined}}
                            </li>
                        </ul>
                    </div>

                </div>
            </div>
            {% endblock %}
        </div>

    </div>
</div>
<script type="text/javascript">
    $(function () {

        $(".menu dt").each(function () {
            $(this).click(function () {
                if ($(this).next().is(":hidden")) {
                    $(this).removeClass("hid");
                    $(this).next().show();
                } else {
                    $(this).addClass("hid");
                    $(this).next().hide();

                }
            });
        });

    });
</script>
{% endblock %}